name: 🚀 Run Python Script and Deploy Changes to omagedex.info
on:
  push:
    branches:
      - main
jobs:
  Run-Python-Script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Install Python 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate HTML
      run: python create_html.py
  FTP-Deploy-Action:
    needs: Run-Python-Script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
